apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
  namespace: kjyo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
