apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharded-redis
  namespace: kjyo
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
