apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kjyo
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    nodePort: 32222
